- name: Jenkins
  hosts: all
  become: true
  
  pre_tasks:
    - name: Pip
      apt: name=python-pip state=present

    - name: Docker-py
      pip:
        name: docker

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Get docker info
      shell: docker info
      register: docker_info
      changed_when: false

    - name: Create primary swarm manager
      shell: docker swarm init
      when: "docker_info.stdout.find('Swarm: inactive') != -1"

    - name: Create secret user
      docker_secret:
        name: jenkins-user
        data: admin
        state: present

    - name: Create secret pass
      docker_secret:
        name: jenkins-pass
        data: adminpass
        state: present

    - name: Start service
      docker_service:
        project_src: /vagrant/app/
        state: present