- name: Jenkins
  hosts: all
  become: true

  pre_tasks:
    - name: Pip
      apt: name=python-pip state=present

    - name: Docker-py
      pip:
        name: docker

    - name: Docker compose
      pip:
        name: docker-compose

  roles:
    - role: geerlingguy.docker
    
  tasks:
    - name: Config docker
      copy: 
        src: files/daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart Docker
      shell: systemctl restart docker

    - name: Create secret user
      docker_secret:
        name: jenkins-user
        data: admin
        state: present

    - name: Create secret pass
      docker_secret:
        name: jenkins-pass
        data: adminpass
        state: present

    - name: Copy Compose file
      copy:
        src: ../app/docker-compose.yml
        dest: /home/docker-compose.yml