version: '3.3'
 
services:
  main:
    image: danielspeixoto/jenkins
    ports:
      - 8080:8080
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - jenkins_home:/var/jenkins_home
    networks: 
      - host
 
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins_home:

networks: 
  host: